# Generated by Django 4.1.6 on 2023-02-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery', 'verbose_name_plural': 'product galleries'},
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='', upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='photos/products/gallery'),
        ),
    ]
